### ISSUE TITLE
Couldn't find preset "stage-0" relative to directory

### ISSUE THREAD

**Issue by abeltje1** [wellguimaraes/actionware#11]
When trying to build my app, I keep getting the next error:  TransformError: /tmp/sandbox/workspace/node_modules/actionware/lib/index.js: Couldn't find preset "stage-0" relative to directory "/tmp/sandbox/workspace/node_modules/actionware". Does anyone have any clue what this means? 

Thanks!

**Comment by wellguimaraes** [comment]
Should be fixed on 8.2.1 ;)
