### ISSUE TITLE
Add ability to add custom prefix and skip withActions 

### ISSUE THREAD

**Issue by zhDmitry** [wellguimaraes/actionware#3]
I have make some changes to api 
[click](https://github.com/wellguimaraes/actionware/compare/master...zhDmitry:master)
it will change api to something like this.
I also added actions args to busy action call.
 But now you will be able to dispatch actions without 
"withActions" hoc
```js 
import { createActions, next } from '@sp/actionware';

const openToolbar = args => args;
const closeToolbar = args => args;

export const actions = createActions(
	{
		openToolbar,
		closeToolbar
	},
	{ prefix: '@toolbar/' }
);

export default actions;
```
What do you think about it ?

**Comment by wellguimaraes** [comment]
Hey @zhDmitry , I saw your changes, and the idea of having args on every event handler actually led me to some changes I pushed yesterday. Do you mind reviewing them ([here](https://github.com/wellguimaraes/actionware#api) and [here](https://github.com/wellguimaraes/actionware#cancel-an-action-execution)) ? 

[These changes](https://github.com/wellguimaraes/actionware/compare/master...zhDmitry:master#diff-52ace21827ea0130a413a22cd1697dc8R110) can cause issues depending on the usage, when the action hasn't been created, that's why I was using the `createAction` fn and checking `_trackedAction` to avoid recreating an action.

About exposing `createActions` and provide a way to have custom prefix, I believe it's a good idea!

The thing about using `withActions` is to improve component testability, but it's good to have both options. ;)

**Comment by zhDmitry** [comment]
It is possible to implement my case with createActions and prefix using helper fn which will be compatible with your code and useful for development
```js
   const bindToStore = (actions, { prefix }) =>
        Object.keys(actions).reduce(( acc, el ) => { 
                const action = actions[el]._trackedActions || createAction();
                const actionName = action._successType;
                action._successType = prefix + actionName
                // additional types mapping ...
                acc[el] = action;
                return acc;
   }, {})
```
What do you think about this ?

**Comment by wellguimaraes** [comment]
@zhDmitry Check [this](https://github.com/wellguimaraes/actionware/tree/dev#after-creating-your-redux-store-let-actionware-know-your-store-instance-optionally-you) and [this](https://github.com/wellguimaraes/actionware/tree/dev#without-injecting-actions-as-props). Do these cover your usage?

**Comment by zhDmitry** [comment]
@wellguimaraes Awesome, thanks man.  
p.s. Do you have any plans for this libs and stateware the idea is awesome ? It reduces a lot of boilerplate code.

**Comment by wellguimaraes** [comment]
Great @zhDmitry ! Thanks for your help!

I'll review these changes, add some tests and then merge them rebase master (and push to npm) branch ASAP.

Regarding **Stateware**, I wanna make some improvements to get rid of the `@getter` hoc and make getters visible so we can see them on the Redux tools. I'm using both libs in a few projects, and I'd love to see more people using it to avoid the boilerplate hell ;)

** I've changed `createActions` a lil bit, so you can easily test components (even not using `withActions`) just mocking the `call` fn with `mockCallWith`. I'll create an example on the README.

**Comment by zhDmitry** [comment]
@wellguimaraes Do you have any todo for actionware ? 

I don't use stateware because i'm afraid performance issues with fn.toString :) 
But it also selectors doesn't critical for me. But it would be cool to implement some helpers for immutable updates using 'immutability-helper' or 'dot-prop-immutable'

```
   return store.update('q.w.e.r.y', (el) => ({  ...el, done: true}) ); 
```

**Comment by wellguimaraes** [comment]
@zhDmitry

> Do you have any todo for actionware ?

Add TS support (create definition files)

> I don't use stateware because i'm afraid performance issues with fn.toString :)

Actually, the fn.toString is done once, and if you're using `@getter` decorator, never... However, the idea is to get rid of both approaches... I've come with an idea (one of those during shower) to make that possible but I still need to try that on code... :P

**Comment by wellguimaraes** [comment]
@zhDmitry 

> But it would be cool to implement some helpers for immutable updates using 'immutability-helper' or 'dot-prop-immutable'

Ohh, cool! I didn't know these two libs! ;) Stateware needs something like that for nested values :D

**Comment by fend25** [comment]
@wellguimaraes 
I don't want to start new issue about this, but what about of replacing withActions with some another binding mechanism without dependencing react?
For example in my current project we are using preact and we don't have react as dependency. I want to use your library, but I cant because of another VDOM library.

**Comment by zhDmitry** [comment]
@fend25 i guess you should implement your own with actions method or add alias for webpack 
and change react to preact.

**Comment by fend25** [comment]
@zhDmitry
What if somebody is using redux with angular? I'm not sure whether the locking to react is a good choice.

**Comment by zhDmitry** [comment]
@fend25 is util hoc. Hoc is only allowed in react and similar frameworks so if you use other framework you should write your own implementation of createActions

**Comment by wellguimaraes** [comment]
@fend25 to use with Preact, a simple alias setup on webpack config file would solve: https://github.com/developit/preact-compat#usage-with-webpack

**Comment by wellguimaraes** [comment]
I'll close it since the issue subject has been solved

**Comment by wellguimaraes** [comment]
I'll close it since the issue subject has been solved

**Comment by wellguimaraes** [comment]
@zhDmitry check the new version of https://github.com/wellguimaraes/stateware

- Dependency-free
- No more fn.toString o/
- No more `@getter` decorator
