### ISSUE TITLE
Problem with multiple redux store

### ISSUE THREAD

**Issue by zhDmitry** [wellguimaraes/actionware#5]
It is not possible to use this library with multiple redux store.
I faced with this problem and decide to rewrite api of actionware using redux middleware.
[click](https://github.com/zhDmitry/rrethunk)

This library in development but it could be a solution

**Comment by wellguimaraes** [comment]
@zhDmitry The idea with Redux is that you use a single store with multiple reducers to separate data domains. Can you describe a scenario where a second (or nth) store is really needed?

**Comment by zhDmitry** [comment]
@wellguimaraes for common usage  you don't need multiple redux store and this approach is wrong but I have what I have. 
In my case I have 3 separated redux store in one app. (this is long story).
I made this issue for people who faced with the same problem.

**Comment by wellguimaraes** [comment]
Got it. :wink:
