### ISSUE TITLE
Spamming actions that are injected with @withActions cause React 16 to throw warnings.

### ISSUE THREAD

**Issue by Fluxarray** [wellguimaraes/actionware#6]
How to reproduce: attach a withActions decorator injected action prop to the onClick of a button and rapidly spam it.

React 16 will throw the following warning for every key (=[someProperty]) of Synthetic event:
"Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `[someProperty]` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information."

**Comment by wellguimaraes** [comment]
@Fluxarray It happens for async actions, when you try to access the synthetic event properties after the action returned a promise. It's not something *actionware* should actually handle (to avoid compromising performance). Anyway, you have these solutions:

1. Destructure the event to get the properties you want on the function signature (or before any async operation):
```js
export async function someAction({ target, clientX }) { ... }
// OR
export async function someAction({ target, clientX }) { 
  const { clientX, clientY, target } = e
  // do whatever you need to do
}
```
2. Use event persist before any async operation inside the action:
```js
export async function someAction(e) { 
  e.persist()
  // do whatever you need to do
}
```

https://codesandbox.io/s/5mx4zoz68n

**Comment by Fluxarray** [comment]
It happened without trying to access the synthetic event, it wasn't an async function. It was a basic increment action to try out Actionware (which seems very satisfactory by the way!).

After coming back to my computer the issue didn't happen anymore.

**Comment by wellguimaraes** [comment]
@Fluxarray Got it. I tried spamming the button with a sync action, and it didn't happen. Anyway, the solutions presented above should take care of this. ;)

BTW, thanks for the repport! ;)

**Comment by Fluxarray** [comment]
When .persist()ing all events, the Redux devtool becomes unusable: it can't even detect Redux is being used.

Seeing as Actionware is Redux based, not being able to use the devtool for debugging seems like a deal-breaker.

**Comment by wellguimaraes** [comment]
@Fluxarray Working normal here... Can you show the setup you're using there?

**Comment by Fluxarray** [comment]
Using almost 'stock' ejected create-react-app.

It seems to be a Redux issue: [https://github.com/zalmoxisus/redux-devtools-extension/issues/315#issuecomment-282656994](url)

**Comment by wellguimaraes** [comment]
https://codesandbox.io/s/5mx4zoz68n

![image](https://user-images.githubusercontent.com/4805500/31152858-0707d42e-a86c-11e7-8287-f187f7f076c1.png)

**Comment by Fluxarray** [comment]
The synthetic event warnings only happen when using hot-loading webpack-dev-server, the built app doesn't have this issue. I also noticed an error buried in the warnings, it fired on every click of a button.

I removed the @withAction decorator and used call() instead, no more issues at all. What could be the cause?

I'm using webpack with babel-polyfill to support decorators, not sure if this is relevant.

**Comment by wellguimaraes** [comment]
>  I also noticed an error buried in the warnings, it fired on every click of a button: "toISOString is not a function". The built app also fired these warnings.

@Fluxarray That's totally new for me. Actionware has no date manipulation, so of course this call to `toISOString` is not made on it.

> I removed the withAction decorator and used call() instead, no more issues at all. What could be the cause?

`withActions` just creates binds of the `call` fn with the given actions as first parameters, so both approaches should behave exactly the same way.

**Comment by wellguimaraes** [comment]
@Fluxarray In case you need any help, let me know on https://gitter.im/actionwarejs/Lobby

**Comment by Fluxarray** [comment]
I set up a Webpack config with HMR from scratch, to rule out any interference from the create-react-app implementation.

Still getting the exact same issue when using HMR: withActions causes synthetic event warnings, while call() does not. When running a production build (= no HMR), withActions does not cause these warnings anymore (it did with create-react-app though).

Still trying to find the cause so it can be resolved.

**Comment by wellguimaraes** [comment]
@Fluxarray can you share this setup on a sandbox platform?
