### ISSUE TITLE
react-native support?

### ISSUE THREAD

**Issue by justinobney** [wellguimaraes/actionware#9]
I am having an issue getting this working in react-native. It appears that the stage-0 dep is causing issues.

using:
* `create-react-native-app`
* `expo (21)`

**Comment by justinobney** [comment]
I was able to use this by compiling and moving the lib folder into my project..

**Comment by wellguimaraes** [comment]
Hey @justinobney, sorry for the delay... I've been out for a while... I never tried using it with React Native, but I'll try and check what I can change to make it fixed. BTW, thanks for the tip!

**Comment by wellguimaraes** [comment]
Should be fixed on 8.2.1
